// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNA6bUoBT18qkU3U4tKBwFOi9OuDSEb6U',
    appId: '1:455194861641:android:5980b8957cf2ce0fd71f98',
    messagingSenderId: '455194861641',
    projectId: 'herstyleproject',
    storageBucket: 'herstyleproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByks8dou2jST3yq9IJU4IflcksZnRIyX0',
    appId: '1:455194861641:ios:2722caff04fa48a4d71f98',
    messagingSenderId: '455194861641',
    projectId: 'herstyleproject',
    storageBucket: 'herstyleproject.firebasestorage.app',
    iosClientId: '455194861641-2c74r085qrnsdrrntdrq3hq1bvfpdqd2.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5i8xBebj6eXHdeVcV5_37Vphi6gVTD9A',
    appId: '1:455194861641:web:3836e2fd0de7649fd71f98',
    messagingSenderId: '455194861641',
    projectId: 'herstyleproject',
    authDomain: 'herstyleproject.firebaseapp.com',
    storageBucket: 'herstyleproject.firebasestorage.app',
    measurementId: 'G-TTENMDBL1V',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByks8dou2jST3yq9IJU4IflcksZnRIyX0',
    appId: '1:455194861641:ios:2722caff04fa48a4d71f98',
    messagingSenderId: '455194861641',
    projectId: 'herstyleproject',
    storageBucket: 'herstyleproject.firebasestorage.app',
    iosClientId: '455194861641-2c74r085qrnsdrrntdrq3hq1bvfpdqd2.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5i8xBebj6eXHdeVcV5_37Vphi6gVTD9A',
    appId: '1:455194861641:web:b7d31fd47b3af4d5d71f98',
    messagingSenderId: '455194861641',
    projectId: 'herstyleproject',
    authDomain: 'herstyleproject.firebaseapp.com',
    storageBucket: 'herstyleproject.firebasestorage.app',
    measurementId: 'G-MLTDLDWPBG',
  );
}
