// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRrGpPr6-ID6IFQ4GoxhGgO1LRbVIM58E',
    appId: '1:908197834599:web:2f033d21f50b6f77ed89c2',
    messagingSenderId: '908197834599',
    projectId: 'styleher-8e2fb',
    authDomain: 'styleher-8e2fb.firebaseapp.com',
    storageBucket: 'styleher-8e2fb.firebasestorage.app',
    measurementId: 'G-21C3928F84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN6qW13a4Lm-Zgf2zch2cfXsjYscSaAts',
    appId: '1:908197834599:android:c25d0fd924df0f94ed89c2',
    messagingSenderId: '908197834599',
    projectId: 'styleher-8e2fb',
    storageBucket: 'styleher-8e2fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDOYTlotT-gQiwIFkhODLycq23BtcX6AU',
    appId: '1:908197834599:ios:9d16fa96742e509bed89c2',
    messagingSenderId: '908197834599',
    projectId: 'styleher-8e2fb',
    storageBucket: 'styleher-8e2fb.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDOYTlotT-gQiwIFkhODLycq23BtcX6AU',
    appId: '1:908197834599:ios:9d16fa96742e509bed89c2',
    messagingSenderId: '908197834599',
    projectId: 'styleher-8e2fb',
    storageBucket: 'styleher-8e2fb.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRrGpPr6-ID6IFQ4GoxhGgO1LRbVIM58E',
    appId: '1:908197834599:web:175d86714f6c887ced89c2',
    messagingSenderId: '908197834599',
    projectId: 'styleher-8e2fb',
    authDomain: 'styleher-8e2fb.firebaseapp.com',
    storageBucket: 'styleher-8e2fb.firebasestorage.app',
    measurementId: 'G-6C7MMJP77R',
  );
}
